// 问卷模块数据源：随访任务通过 questionnaireCode 绑定这里的模块。
window.QUESTIONNAIRE_MODULES = {
  SC: {
    code: 'SC',
    name: '首次建档随访问卷',
    moduleId: 50,
    questions: [
      {
        id: 492,
        answerType: 0,
        sort: 1,
        title: '身份与后续联系人',
        questionName: '您是患者本人吗？后续随访是继续联系您吗？',
        createTime: '2026-03-30 09:58:51',
        updateTime: '2026-03-30 09:58:51',
        options: [
          { answerText: '是本人，随访可联系本人', sort: 1, isText: 1 },
          { answerText: '是本人，后续随访可能不便，需要联系代访人员（子女/配偶/监护人……)', sort: 2, isText: 0, textTip: '请记录关系和联系手机号' },
          { answerText: '不是本人，随访需要联系代访人员（子女/配偶/监护人……)', sort: 3, isText: 0, textTip: '请记录关系和联系手机号' },
        ],
      },
      {
        id: 493,
        answerType: 0,
        sort: 2,
        title: '登记信息',
        questionName: '我先帮您（或您父亲/您母亲/您太太/您先生……）登记一下基础信息，医生给您（或您父亲/您母亲/您太太/您先生……）处方上写的适应症是什么？（单选，必填，如患者表述不清可提醒查看病历）',
        createTime: '2026-03-30 10:07:09',
        updateTime: '2026-03-30 10:07:09',
        options: ['非小细胞肺癌', '小细胞肺癌', '肾癌', '尿路上皮癌', '食管癌', '鼻咽癌', '头颈鳞癌', '三阴乳腺癌', '乳腺癌（三阴以外）', '淋巴瘤', '黑色素瘤', '肝癌', '胃癌', '结直肠癌', '肉瘤', '胆道癌', '胰腺癌', '宫颈癌', '卵巢癌'].map((answerText, index) => ({ answerText, sort: index + 1, isText: 1 })).concat([{ answerText: '其他', sort: 20, isText: 0, textTip: '请记录具体适应症' }]),
      },
      {
        id: 494,
        answerType: 0,
        sort: 3,
        title: '疾病分期',
        questionName: '您知道您（或您父亲/您母亲/您太太/您先生……）现在是几期了吗？',
        createTime: '2026-03-30 10:14:18',
        updateTime: '2026-03-30 10:14:18',
        options: ['I期', 'II期', 'III期', 'IV期', '局部晚期', '转移性', '广泛期_仅小细胞肺癌'].map((answerText, index) => ({ answerText, sort: index + 1, isText: 1 })),
      },
      {
        id: 495,
        answerType: 0,
        sort: 4,
        title: '治疗方案',
        questionName: '您（或您父亲/您母亲/您太太/您先生……）目前是用的什么治疗方案？',
        createTime: '2026-03-30 11:01:38',
        updateTime: '2026-03-30 11:01:38',
        options: ['一线治疗_1L', '一线治疗_1L（含转化治疗）_仅肝癌', '二线治疗_2L', '三线及以上治疗_3L及以上', '诱导治疗_仅鼻咽癌', '新辅助（可手术的）_仅肝癌', '新辅助', '辅助', '保膀胱_仅尿路上皮癌', 'NMIBC_仅尿路上皮癌', '围术期_仅非小细胞肺癌', 'SCLC_仅小细胞癌'].map((answerText, index) => ({ answerText, sort: index + 1, isText: 1 })),
      },
      {
        id: 515,
        answerType: 0,
        sort: 5,
        title: '联合用药',
        questionName: '您（或您父亲/您母亲/您太太/您先生……）目前是否联合用药？',
        createTime: '2026-03-30 11:03:44',
        updateTime: '2026-03-30 11:03:44',
        options: [
          { answerText: '拓益单药治疗', sort: 13, isText: 1 },
          { answerText: '拓益联合化疗药，记录药品名称', sort: 14, isText: 0, textTip: '记录药品名称' },
          { answerText: '拓益联合靶向药，记录药品名称', sort: 15, isText: 0, textTip: '记录药品名称' },
          { answerText: '拓益联合其他药，记录药品名称', sort: 16, isText: 0, textTip: '记录药品名称' },
        ],
      },
      {
        id: 514,
        answerType: 0,
        sort: 6,
        title: '是否手术',
        questionName: '您（或您父亲/您母亲/您太太/您先生……）目前是用的什么治疗方案，有没有手术过？',
        createTime: '2026-03-30 11:04:45',
        updateTime: '2026-03-30 11:04:45',
        options: ['已手术', '未手术'].map((answerText, index) => ({ answerText, sort: index + 1, isText: 1 })),
      },
      {
        id: 516,
        answerType: 0,
        sort: 7,
        title: '是否复发/转移',
        questionName: '您（或您父亲/您母亲/您太太/您先生……）目前是否复发/转移？',
        createTime: '2026-03-30 11:06:02',
        updateTime: '2026-03-30 11:06:02',
        options: ['复发', '转移', '无转移', '铂类化疗失败_仅尿路上皮癌'].map((answerText, index) => ({ answerText, sort: index + 19, isText: 1 })),
      },
      {
        id: 496,
        answerType: 0,
        sort: 8,
        title: '复诊周期',
        questionName: '那医嘱是让您（或您父亲/您母亲/您太太/您先生……）每2周一次去复诊用药，还是每3周一次？',
        createTime: '2026-04-07 15:16:00',
        updateTime: '2026-04-07 15:16:00',
        options: ['每2周一次', '每3周一次'].map((answerText, index) => ({ answerText, sort: index + 1, isText: 1 })),
      },
      {
        id: 497,
        answerType: 0,
        sort: 9,
        title: '症状变化',
        questionName: '您（或您父亲/您母亲/您太太/您先生……）这几天用完药，自己感觉症状有没有变化？是不是比之前还好一些？',
        createTime: '2026-03-30 11:09:51',
        updateTime: '2026-03-30 11:09:51',
        options: [
          { answerText: '没变化，挺稳定', sort: 1, isText: 1, keyword: '症状稳定' },
          { answerText: '好转了', sort: 2, isText: 1, keyword: '症状好转' },
          { answerText: '加重了', sort: 3, isText: 1, keyword: '症状加重' },
          { answerText: '其他变化（您说一下：______）', sort: 4, isText: 0, keyword: '症状其他变化', textTip: '请记录具体变化' },
        ],
      },
      {
        id: 498,
        answerType: 1,
        sort: 10,
        title: '不良反应',
        questionName: '您（或您父亲/您母亲/您太太/您先生……）这几天吃饭睡觉都还正常吧？有没有出现不舒服的症状？（多选，必填）',
        createTime: '2026-03-30 11:13:32',
        updateTime: '2026-03-30 11:13:32',
        options: ['没有不舒服', '食欲减退', '恶心呕吐', '腹泻', '发热', '乏力', '头痛', '失眠', '皮疹瘙痒', '口腔溃疡', '心律失常', '关节痛', '咳嗽', '胸闷呼吸困难', '免疫性肺炎', '免疫性腹泻/结肠炎', '免疫性肝炎', '免疫性肾炎', '免疫性甲状腺功能异常(甲减/甲亢)', '免疫性高血糖症或一型糖尿病', '免疫性皮疹', '血小板减少', '血淀粉酶升高或脂肪酶升高', '胰腺炎', '心肌炎', '重症肌无力', '脑炎'].map((answerText, index) => ({ answerText, sort: index + 1, isText: 1, keyword: index === 0 ? '无不良反应' : '有不良反应' })).concat([{ answerText: '其他（您详细说一下，我看看是不是需要去医院让医生处理：______）', sort: 28, isText: 0, keyword: '有不良反应', textTip: '请记录其他不适症状' }]),
      },
    ],
  },
  FG: {
    code: 'FG',
    name: '复购随访问卷',
    moduleId: 51,
    questions: [
      {
        id: 502,
        answerType: 0,
        sort: 1,
        title: '用药情况',
        questionName: '先和您确认一下，您（或您父亲/您母亲/您太太/您先生……）现在还是按照医嘱在正常用药对吧？医生有没有调整用药方案或者剂量？',
        createTime: '2026-03-30 11:34:53',
        updateTime: '2026-03-30 11:34:53',
        isTriggered: 1,
        options: [
          { answerText: '正常用药，没有调整剂量', sort: 1, isText: 1 },
          { answerText: '正常用药，医生调整剂量', sort: 2, isText: 0, keyword: '调整剂量', followUpScripId: 447, textTip: '填写医生调整剂量原因和现在的剂量' },
          { answerText: '自己减药了', sort: 3, isText: 1, relatedQuestionId: '504' },
          { answerText: '医生让停药了', sort: 4, isText: 0, keyword: '医嘱减量', followUpScripId: 448, textTip: '填写医生停药原因' },
          { answerText: '自己停药了', sort: 5, isText: 1, relatedQuestionId: '505' },
          { answerText: '医生让推迟用药了（医嘱推迟）', sort: 6, isText: 0, keyword: '医嘱推迟', followUpScripId: 449, textTip: '填写医生推迟原因' },
          { answerText: '自己推迟用药了', sort: 7, isText: 1, relatedQuestionId: '503' },
        ],
      },
      {
        id: 503,
        answerType: 0,
        sort: 2,
        title: '您是什么原因推迟呢？',
        questionName: '您是什么原因推迟呢？',
        createTime: '2026-03-30 11:38:26',
        updateTime: '2026-03-30 11:38:26',
        isTriggered: 0,
        triggerRules: [{ relationId: 502, optionValues: ['自己推迟用药了'] }],
        options: [
          { answerText: '挂不上主治医生的号，被迫延后', sort: 2, isText: 1, keyword: '挂不上号', followUpScripId: 450 },
          { answerText: '感觉病情比较稳定，主动延后复诊', sort: 3, isText: 1, keyword: '感觉病情稳定', followUpScripId: 451 },
          { answerText: '最近比较忙，没时间去复诊', sort: 4, isText: 1, keyword: '最近忙', followUpScripId: 452 },
          { answerText: '其他原因推迟', sort: 5, isText: 0, keyword: '其他原因推迟', followUpScripId: 453, textTip: '填写原因' },
        ],
      },
      {
        id: 504,
        answerType: 0,
        sort: 3,
        title: '您是什么原因想要减药？',
        questionName: '您是什么原因想要减药？',
        createTime: '2026-03-30 11:42:30',
        updateTime: '2026-03-30 11:42:30',
        isTriggered: 0,
        triggerRules: [{ relationId: 502, optionValues: ['自己减药了'] }],
        options: [
          { answerText: '经济原因', sort: 1, isText: 1, keyword: '经济原因', followUpScripId: 454 },
          { answerText: '医保原因', sort: 2, isText: 1, keyword: '医保原因', followUpScripId: 455 },
          { answerText: '觉得治疗没效果', sort: 3, isText: 1, keyword: '觉得治疗没效果', followUpScripId: 456 },
          { answerText: '觉得有副作用', sort: 4, isText: 1, keyword: '觉得有副作用', followUpScripId: 457 },
          { answerText: '觉得已经好了', sort: 5, isText: 1, keyword: '觉得已经好了', followUpScripId: 458 },
          { answerText: '其他原因想要自行减药', sort: 6, isText: 0, keyword: '其他原因减量', followUpScripId: 459, textTip: '记录详细原因' },
        ],
      },
      {
        id: 505,
        answerType: 0,
        sort: 4,
        title: '您是什么原因想要停药？',
        questionName: '您是什么原因想要停药？',
        createTime: '2026-03-30 11:36:35',
        updateTime: '2026-03-30 11:36:35',
        isTriggered: 0,
        triggerRules: [{ relationId: 502, optionValues: ['自己停药了'] }],
        options: [
          { answerText: '经济原因', sort: 1, isText: 1, isSummary: 1, keyword: '经济原因', followUpScripId: 460 },
          { answerText: '医保原因', sort: 2, isText: 1, isSummary: 1, keyword: '医保原因', followUpScripId: 461 },
          { answerText: '觉得治疗没效果', sort: 3, isText: 1, isSummary: 1, keyword: '觉得治疗没效果', followUpScripId: 462 },
          { answerText: '觉得有副作用', sort: 4, isText: 1, isSummary: 1, keyword: '觉得有副作用', followUpScripId: 463 },
          { answerText: '觉得已经好了', sort: 5, isText: 1, isSummary: 1, keyword: '觉得已经好了', followUpScripId: 464 },
          { answerText: '在外地不方便', sort: 5, isText: 1, isSummary: 1, keyword: '在外地不方便', followUpScripId: 465 },
          { answerText: '其他原因想要自行停药', sort: 6, isText: 0, isSummary: 1, keyword: '其他原因停药', followUpScripId: 466, textTip: '记录详细原因' },
        ],
      },
      {
        id: 506,
        answerType: 0,
        sort: 5,
        title: '症状变化',
        questionName: '您（或您父亲/您母亲/您太太/您先生……）这一段时间用完药，自己感觉症状有没有变化？是不是比之前还好一些？',
        createTime: '2026-03-30 12:14:08',
        updateTime: '2026-03-30 12:14:08',
        isTriggered: 1,
        options: [
          { answerText: '没变化，挺稳定', sort: 1, isText: 1, keyword: '症状稳定', followUpScripId: 467 },
          { answerText: '好转了', sort: 2, isText: 1, keyword: '症状好转', followUpScripId: 468 },
          { answerText: '加重了', sort: 3, isText: 1, keyword: '症状加重', followUpScripId: 469 },
          { answerText: '其他变化', sort: 4, isText: 0, keyword: '其他变化', followUpScripId: 470, textTip: '记录变化' },
        ],
      },
      {
        id: 507,
        answerType: 1,
        sort: 6,
        title: '不良反应',
        questionName: '您（或您父亲/您母亲/您太太/您先生……）这一段时间吃饭睡觉都还正常吧？（如上次随访记录过不良反应，请询问：有没有像上次出现食欲减退/恶心呕吐/腹泻/发热……的情况？）',
        createTime: '2026-03-24 17:51:25',
        updateTime: '2026-03-24 17:51:25',
        isTriggered: 1,
        options: ['没有不舒服', '食欲减退', '恶心呕吐', '腹泻', '发热', '乏力', '头痛', '失眠', '皮疹瘙痒', '口腔溃疡', '心律失常', '关节痛', '咳嗽', '胸闷呼吸困难', '免疫性肺炎', '免疫性腹泻/结肠炎', '免疫性肝炎', '免疫性肾炎', '免疫性甲状腺功能异常(甲减/甲亢)', '免疫性高血糖症或一型糖尿病', '免疫性皮疹', '血小板减少', '血淀粉酶升高或脂肪酶升高', '胰腺炎', '心肌炎', '重症肌无力', '脑炎'].map((answerText, index) => ({ answerText, sort: index + 1, isText: 1, keyword: index === 0 ? '无不良反应' : '有不良反应', followUpScripId: index === 0 ? 445 : 446, isSummary: answerText === '腹泻' ? 1 : 0 })).concat([{ answerText: '其他（您详细说一下，我看看是不是需要去医院让医生处理：______）', sort: 28, isText: 0, keyword: '有不良反应', followUpScripId: 446, textTip: '请记录其他不适症状' }]),
      },
      {
        id: 508,
        answerType: 0,
        sort: 7,
        title: '合并症',
        questionName: '您（或您父亲/您母亲/您太太/您先生……）这段时间有没有新增其他合并症？比如三高、肺炎、关节疼痛等',
        createTime: '2026-03-30 13:59:13',
        updateTime: '2026-03-30 13:59:13',
        isTriggered: 1,
        options: [
          { answerText: '没有', sort: 1, isText: 1 },
          { answerText: '有', sort: 2, isText: 0, textTip: '请记录合并症' },
        ],
      },
      {
        id: 509,
        answerType: 1,
        sort: 8,
        title: '您还有其他问题需要问我的吗？',
        questionName: '您还有其他问题需要问我的吗？',
        script: '<p>（若有，请选择问题分类并填写具体问题，需完整记录，多选）</p>',
        createTime: '2026-03-30 14:03:03',
        updateTime: '2026-03-30 14:03:03',
        isTriggered: 1,
        followUpScripId: 471,
        options: [
          { answerText: '无', sort: 1, isText: 1, isSummary: 1 },
          { answerText: '药物治疗周期问题', sort: 2, isText: 0, textTip: '具体问题' },
          { answerText: '复发问题', sort: 3, isText: 1 },
          { answerText: '副作用 / 不良反应相关', sort: 4, isText: 0, textTip: '具体问题' },
          { answerText: '耐药问题', sort: 5, isText: 1 },
          { answerText: '安全性问题', sort: 6, isText: 0, textTip: '具体问题' },
          { answerText: '药物疗效相关', sort: 7, isText: 1 },
          { answerText: '用药方式', sort: 8, isText: 0, textTip: '具体问题' },
          { answerText: '用药时长', sort: 9, isText: 1 },
          { answerText: '医保费用', sort: 10, isText: 0, textTip: '具体问题' },
          { answerText: '购买渠道', sort: 11, isText: 1 },
          { answerText: '复诊复查/就医流程', sort: 12, isText: 0, textTip: '具体问题' },
          { answerText: '日常生活问题（饮食、运动、康复等）', sort: 13, isText: 1 },
          { answerText: '其他', sort: 14, isText: 0, textTip: '具体问题' },
        ],
      },
    ],
  },
  CQ: {
    code: 'CQ',
    name: '超期随访问卷',
    moduleId: 52,
    questions: [
      {
        id: 510,
        answerType: 0,
        sort: 1,
        title: '用药情况',
        questionName: '您是不是还在正常用药？医生有给您调整用药方案吗？',
        createTime: '2026-03-30 14:12:45',
        updateTime: '2026-03-30 14:12:45',
        isTriggered: 1,
        options: [
          { answerText: '正常用药，去其他药房拿药了', sort: 1, isText: 1, keyword: '换药房拿药', followUpScripId: 472 },
          { answerText: '医生让停药了', sort: 2, isText: 0, keyword: '医嘱停药', followUpScripId: 473, textTip: '填写医生停药原因' },
          { answerText: '自己停药了', sort: 3, isText: 1 },
          { answerText: '医生让推迟用药了（医嘱推迟）', sort: 4, isText: 0, keyword: '医嘱推迟', followUpScripId: 474, textTip: '填写医生推迟原因' },
          { answerText: '自己推迟用药了', sort: 5, isText: 1 },
          { answerText: '其他原因推迟', sort: 6, isText: 1, keyword: '其他原因推迟', followUpScripId: 475 },
          { answerText: '其他原因想要自行停药', sort: 7, isText: 0, keyword: '其他原因自行停药', followUpScripId: 476, textTip: '记录详细原因' },
        ],
      },
      {
        id: 511,
        answerType: 0,
        sort: 2,
        title: '您是什么原因推迟呢？',
        questionName: '您是什么原因推迟呢？',
        createTime: '2026-03-30 14:25:40',
        updateTime: '2026-03-30 14:25:40',
        isTriggered: 0,
        triggerRules: [{ relationId: 510, optionValues: ['自己推迟用药了'] }],
        options: [
          { answerText: '挂不上主治医生的号，被迫延后', sort: 2, isText: 1, keyword: '挂不上号', followUpScripId: 450 },
          { answerText: '感觉病情比较稳定，主动延后复诊', sort: 3, isText: 1, keyword: '感觉病情稳定', followUpScripId: 451 },
          { answerText: '最近比较忙，没时间去复诊', sort: 4, isText: 1, keyword: '最近忙', followUpScripId: 452 },
          { answerText: '其他原因推迟', sort: 5, isText: 0, keyword: '其他原因推迟', followUpScripId: 453, textTip: '填写原因' },
        ],
      },
      {
        id: 512,
        answerType: 0,
        sort: 3,
        title: '您是什么原因想要停药？',
        questionName: '您是什么原因想要停药？',
        createTime: '2026-03-30 14:25:46',
        updateTime: '2026-03-30 14:25:47',
        isTriggered: 0,
        triggerRules: [{ relationId: 510, optionValues: ['自己停药了'] }],
        options: [
          { answerText: '经济原因', sort: 1, isText: 1, keyword: '经济原因', followUpScripId: 460 },
          { answerText: '医保原因', sort: 2, isText: 1, keyword: '医保原因', followUpScripId: 461 },
          { answerText: '觉得治疗没效果', sort: 3, isText: 1, keyword: '觉得治疗没效果', followUpScripId: 462 },
          { answerText: '觉得有副作用', sort: 4, isText: 1, keyword: '觉得有副作用', followUpScripId: 463 },
          { answerText: '觉得已经好了', sort: 5, isText: 1, keyword: '觉得已经好了', followUpScripId: 464 },
          { answerText: '在外地不方便', sort: 5, isText: 1, keyword: '在外地不方便', followUpScripId: 465 },
          { answerText: '其他原因想要自行停药', sort: 6, isText: 0, keyword: '其他原因停药', followUpScripId: 466, textTip: '记录详细原因' },
          { answerText: '放弃治疗', sort: 8, isText: 1, keyword: '放弃治疗', followUpScripId: 477 },
        ],
      },
      {
        id: 513,
        answerType: 1,
        sort: 4,
        title: '不良反应',
        questionName: '具体的不良反应是？',
        createTime: '2026-03-30 14:27:05',
        updateTime: '2026-03-30 14:27:05',
        isTriggered: 0,
        triggerRules: [{ relationId: 512, optionValues: ['觉得有副作用'] }],
        options: ['食欲减退', '恶心呕吐', '腹泻', '发热', '乏力', '头痛', '失眠', '皮疹瘙痒', '口腔溃疡', '心律失常', '关节痛', '咳嗽', '胸闷呼吸困难', '免疫性肺炎', '免疫性腹泻/结肠炎', '免疫性肝炎', '免疫性肾炎', '免疫性甲状腺功能异常(甲减/甲亢)', '免疫性高血糖症或一型糖尿病', '免疫性皮疹', '血小板减少', '血淀粉酶升高或脂肪酶升高', '胰腺炎', '心肌炎', '重症肌无力', '脑炎'].map((answerText, index) => ({ answerText, sort: index + 2, isText: 1, keyword: '有不良反应', followUpScripId: 446 })).concat([{ answerText: '其他（您详细说一下，我看看是不是需要去医院让医生处理：______）', sort: 28, isText: 0, keyword: '有不良反应', followUpScripId: 446, textTip: '记录不良反应' }]),
      },
    ],
  },
};
